CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     user_name CHARACTER VARYING(255) NOT NULL,
                                     user_email CHARACTER VARYING(500) NOT NULL UNIQUE
);